#! /usr/bin/env python3
from kenken_src import build_smt, parse_kenken
from sys import stdin


if __name__ == "__main__":
    # read puzzle from stdin, parse it, build the smt for it
    # and outut it to stdout.
    print(build_smt(parse_kenken(stdin.read().splitlines()[1:])))
